name: Build

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build GitHubActions/GitHubActions.csproj --no-restore
    - name: Test
      run: dotnet test GitHubActions/GitHubActions.csproj --no-build --verbosity normal
